USE [master]
GO

CREATE DATABASE [I2B2Census]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'I2B2Census_data_01', FILENAME = N'G:\MSSQL12.MSSQLSERVER\MSSQL\Data\i2b2Census_data_01.mdf' , SIZE = 128MB , MAXSIZE = 1024MB , FILEGROWTH = 10MB ),
( NAME = N'I2B2Census_data_02', FILENAME = N'G:\MSSQL12.MSSQLSERVER\MSSQL\Data\i2b2Census_data_02.mdf' , SIZE = 128MB , MAXSIZE = 1024MB , FILEGROWTH = 10MB )
 LOG ON 
( NAME = N'I2B2Census_log_01', FILENAME = N'H:\MSSQL12.MSSQLSERVER\MSSQL\Transaction_Logs\I2B2Census_log_01.ldf' , SIZE = 10MB , MAXSIZE = 1GB , FILEGROWTH = 10MB )

